# Generated by Django 6.0.2 on 2026-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.CharField(blank=True, choices=[('Operations', 'Operations'), ('Intelligence', 'Intelligence'), ('Security', 'Security'), ('Logistics', 'Logistics'), ('Strategy', 'Strategy')], max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('Recruit', 'Recruit'), ('Associate', 'Associate'), ('Soldier', 'Soldier'), ('Caporegime', 'Caporegime'), ('Underboss', 'Underboss')], default='Recruit', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='territory',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
